"""Add foreign key to health_checks

Revision ID: 2e833b5eada7
Revises: 3f07f81e1dcf
Create Date: 2025-11-03 10:06:30.715318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e833b5eada7'
down_revision: Union[str, None] = '3f07f81e1dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'health_checks', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_checks', type_='foreignkey')
    # ### end Alembic commands ###
