"""Initial schema setup

Revision ID: 3f07f81e1dcf
Revises: 
Create Date: 2025-11-03 09:55:23.402539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f07f81e1dcf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), server_default='NOW()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_checks_service_time', 'health_checks', ['service_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_health_checks_checked_at'), 'health_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_health_checks_service_id'), 'health_checks', ['service_id'], unique=False)
    op.create_table('pending_alert_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_key', sa.String(length=255), nullable=False),
    sa.Column('alert_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_batches_expires', 'pending_alert_batches', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pending_alert_batches_batch_key'), 'pending_alert_batches', ['batch_key'], unique=False)
    op.create_index(op.f('ix_pending_alert_batches_expires_at'), 'pending_alert_batches', ['expires_at'], unique=False)
    op.create_table('report_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('jalali_day_of_week', sa.Integer(), nullable=True),
    sa.Column('jalali_day_of_month', sa.Integer(), nullable=True),
    sa.Column('jalali_month', sa.Integer(), nullable=True),
    sa.Column('target_user_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('expected_status_code', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('api_provider', sa.String(length=100), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('credit_threshold', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credit_check_interval_hours', sa.Integer(), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('service_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'environment', name='uq_service_name_env')
    )
    op.create_index('idx_services_active_env', 'services', ['is_active', 'environment'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='NOW()', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('alert_archive_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('archive_after_days', sa.Integer(), nullable=False),
    sa.Column('auto_archive_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_logs', sa.JSON(), nullable=False),
    sa.Column('notified_user_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('telegram_message_ids', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alerts_service_unresolved', 'alerts', ['service_id', 'resolved_at'], unique=False, postgresql_where='resolved_at IS NULL')
    op.create_index(op.f('ix_alerts_service_id'), 'alerts', ['service_id'], unique=False)
    op.create_table('muted_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('muted_by_command', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_id', name='uq_muted_user_service')
    )
    op.create_index('idx_muted_services_active', 'muted_services', ['user_id', 'service_id', 'muted_until'], unique=False)
    op.create_index(op.f('ix_muted_services_service_id'), 'muted_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_muted_services_user_id'), 'muted_services', ['user_id'], unique=False)
    op.create_table('user_service_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('can_receive_alerts', sa.Boolean(), nullable=False),
    sa.Column('can_mute', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_id', name='uq_user_service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_service_permissions')
    op.drop_index(op.f('ix_muted_services_user_id'), table_name='muted_services')
    op.drop_index(op.f('ix_muted_services_service_id'), table_name='muted_services')
    op.drop_index('idx_muted_services_active', table_name='muted_services')
    op.drop_table('muted_services')
    op.drop_index(op.f('ix_alerts_service_id'), table_name='alerts')
    op.drop_index('idx_alerts_service_unresolved', table_name='alerts', postgresql_where='resolved_at IS NULL')
    op.drop_index('idx_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('alert_archive_config')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_index('idx_services_active_env', table_name='services')
    op.drop_table('services')
    op.drop_table('report_schedules')
    op.drop_index(op.f('ix_pending_alert_batches_expires_at'), table_name='pending_alert_batches')
    op.drop_index(op.f('ix_pending_alert_batches_batch_key'), table_name='pending_alert_batches')
    op.drop_index('idx_pending_batches_expires', table_name='pending_alert_batches')
    op.drop_table('pending_alert_batches')
    op.drop_index(op.f('ix_health_checks_service_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_checked_at'), table_name='health_checks')
    op.drop_index('idx_health_checks_service_time', table_name='health_checks')
    op.drop_table('health_checks')
    # ### end Alembic commands ###
